// Code generated by goctl. DO NOT EDIT!
// Source: goZeroDemo.proto

package goZeroDemo

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GoZeroDemo interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultGoZeroDemo struct {
		cli zrpc.Client
	}
)

func NewGoZeroDemo(cli zrpc.Client) GoZeroDemo {
	return &defaultGoZeroDemo{
		cli: cli,
	}
}

func (m *defaultGoZeroDemo) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := NewGoZeroDemoClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
