// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package user

import (
	"context"

	"goZeroDemo/Users/thy/Downloads/git/types/goZeroDemo"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IdRequest    = goZeroDemo.IdRequest
	UserResponse = goZeroDemo.UserResponse

	User interface {
		GetUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	client := goZeroDemo.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}
