// Code generated by goctl. DO NOT EDIT!
// Source: goZeroDemo.proto

package server

import (
	"context"

	"goZeroDemo/Users/thy/Downloads/git/gozerodemo"
	"goZeroDemo/Users/thy/Downloads/git/internal/logic"
	"goZeroDemo/Users/thy/Downloads/git/internal/svc"
)

type GoZeroDemoServer struct {
	svcCtx *svc.ServiceContext
	goZeroDemo.UnimplementedGoZeroDemoServer
}

func NewGoZeroDemoServer(svcCtx *svc.ServiceContext) *GoZeroDemoServer {
	return &GoZeroDemoServer{
		svcCtx: svcCtx,
	}
}

func (s *GoZeroDemoServer) Ping(ctx context.Context, in *goZeroDemo.Request) (*goZeroDemo.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
