// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"goZeroDemo/Users/thy/Downloads/git/internal/logic"
	"goZeroDemo/Users/thy/Downloads/git/internal/svc"
	"goZeroDemo/Users/thy/Downloads/git/types/goZeroDemo"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	goZeroDemo.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *goZeroDemo.IdRequest) (*goZeroDemo.UserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
